import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Initial schema migration — creates all tables from scratch.
 * All primary keys are UUID v4, generated by PostgreSQL uuid-ossp extension.
 * Entities with user-facing names include a slug column for clean URLs.
 */
export class InitialSchema1712592000000 implements MigrationInterface {
  name = 'InitialSchema1712592000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Extensions
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "pg_trgm"`);

    // ── tenants ──
    await queryRunner.query(`
      CREATE TABLE "tenants" (
        "id"               UUID DEFAULT uuid_generate_v4() NOT NULL,
        "name"             VARCHAR(255) NOT NULL,
        "slug"             VARCHAR(100) NOT NULL,
        "plan"             VARCHAR(50) NOT NULL DEFAULT 'free',
        "settings"         JSONB NOT NULL DEFAULT '{}',
        "max_connections"  INTEGER NOT NULL DEFAULT 5,
        "max_users"        INTEGER NOT NULL DEFAULT 10,
        "is_active"        BOOLEAN NOT NULL DEFAULT true,
        "created_at"       TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at"       TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_tenants" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_tenants_slug" UNIQUE ("slug")
      )
    `);

    // ── users ──
    await queryRunner.query(`
      CREATE TABLE "users" (
        "id"              UUID DEFAULT uuid_generate_v4() NOT NULL,
        "tenant_id"       UUID NOT NULL,
        "email"           VARCHAR(255) NOT NULL,
        "display_name"    VARCHAR(255) NOT NULL,
        "password_hash"   VARCHAR(255),
        "avatar_url"      VARCHAR(500),
        "role"            VARCHAR(50) NOT NULL DEFAULT 'viewer',
        "auth_provider"   VARCHAR(50) NOT NULL DEFAULT 'local',
        "external_id"     VARCHAR(255),
        "last_login_at"   TIMESTAMPTZ,
        "is_active"       BOOLEAN NOT NULL DEFAULT true,
        "created_at"      TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at"      TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_users" PRIMARY KEY ("id"),
        CONSTRAINT "FK_users_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_users_tenant_email" ON "users" ("tenant_id", "email")`);
    await queryRunner.query(`CREATE INDEX "IDX_users_tenant" ON "users" ("tenant_id")`);

    // ── db_connections ──
    await queryRunner.query(`
      CREATE TABLE "db_connections" (
        "id"                 UUID DEFAULT uuid_generate_v4() NOT NULL,
        "tenant_id"          UUID NOT NULL,
        "name"               VARCHAR(255) NOT NULL,
        "slug"               VARCHAR(300) NOT NULL,
        "engine"             VARCHAR(50) NOT NULL,
        "host"               VARCHAR(255) NOT NULL,
        "port"               INTEGER NOT NULL,
        "database_name"      VARCHAR(255) NOT NULL,
        "username"           VARCHAR(255) NOT NULL,
        "vault_secret_path"  VARCHAR(500),
        "encrypted_password" TEXT,
        "use_ssl"            BOOLEAN NOT NULL DEFAULT true,
        "ssl_ca_cert"        TEXT,
        "connection_options" JSONB NOT NULL DEFAULT '{}',
        "last_tested_at"     TIMESTAMPTZ,
        "last_test_status"   VARCHAR(50),
        "is_active"          BOOLEAN NOT NULL DEFAULT true,
        "created_by"         UUID,
        "created_at"         TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at"         TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_db_connections" PRIMARY KEY ("id"),
        CONSTRAINT "FK_db_connections_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_db_connections_tenant_name" ON "db_connections" ("tenant_id", "name")`);
    await queryRunner.query(`CREATE INDEX "IDX_db_connections_tenant" ON "db_connections" ("tenant_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_db_connections_slug" ON "db_connections" ("slug")`);

    // ── analysis_jobs ──
    await queryRunner.query(`
      CREATE TABLE "analysis_jobs" (
        "id"                UUID DEFAULT uuid_generate_v4() NOT NULL,
        "tenant_id"         UUID NOT NULL,
        "connection_id"     UUID NOT NULL,
        "status"            VARCHAR(50) NOT NULL DEFAULT 'pending',
        "progress"          INTEGER NOT NULL DEFAULT 0,
        "total_objects"     INTEGER,
        "processed_objects" INTEGER NOT NULL DEFAULT 0,
        "error_message"     TEXT,
        "error_details"     JSONB,
        "started_at"        TIMESTAMPTZ,
        "completed_at"      TIMESTAMPTZ,
        "triggered_by"      UUID,
        "created_at"        TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_analysis_jobs" PRIMARY KEY ("id"),
        CONSTRAINT "FK_analysis_jobs_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_analysis_jobs_connection" FOREIGN KEY ("connection_id") REFERENCES "db_connections"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_analysis_jobs_tenant" ON "analysis_jobs" ("tenant_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_analysis_jobs_connection" ON "analysis_jobs" ("connection_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_analysis_jobs_status" ON "analysis_jobs" ("status")`);

    // ── discovered_schemas ──
    await queryRunner.query(`
      CREATE TABLE "discovered_schemas" (
        "id"             UUID DEFAULT uuid_generate_v4() NOT NULL,
        "tenant_id"      UUID NOT NULL,
        "connection_id"  UUID NOT NULL,
        "schema_name"    VARCHAR(255) NOT NULL,
        "slug"           VARCHAR(300) NOT NULL,
        "catalog_name"   VARCHAR(255),
        "object_counts"  JSONB NOT NULL DEFAULT '{}',
        "size_bytes"     BIGINT,
        "owner"          VARCHAR(255),
        "first_seen_at"  TIMESTAMPTZ NOT NULL DEFAULT now(),
        "last_seen_at"   TIMESTAMPTZ NOT NULL DEFAULT now(),
        "created_at"     TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_discovered_schemas" PRIMARY KEY ("id"),
        CONSTRAINT "FK_discovered_schemas_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_discovered_schemas_connection" FOREIGN KEY ("connection_id") REFERENCES "db_connections"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_discovered_schemas_conn_catalog_name" ON "discovered_schemas" ("connection_id", "catalog_name", "schema_name")`);
    await queryRunner.query(`CREATE INDEX "IDX_discovered_schemas_tenant" ON "discovered_schemas" ("tenant_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_discovered_schemas_connection" ON "discovered_schemas" ("connection_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_discovered_schemas_slug" ON "discovered_schemas" ("slug")`);

    // ── discovered_tables ──
    await queryRunner.query(`
      CREATE TABLE "discovered_tables" (
        "id"                   UUID DEFAULT uuid_generate_v4() NOT NULL,
        "tenant_id"            UUID NOT NULL,
        "connection_id"        UUID NOT NULL,
        "schema_id"            UUID NOT NULL,
        "schema_name"          VARCHAR(255) NOT NULL,
        "table_name"           VARCHAR(255) NOT NULL,
        "slug"                 VARCHAR(500) NOT NULL,
        "full_qualified_name"  VARCHAR(1000) NOT NULL,
        "table_type"           VARCHAR(50) NOT NULL DEFAULT 'table',
        "estimated_row_count"  BIGINT,
        "size_bytes"           BIGINT,
        "columns"              JSONB NOT NULL DEFAULT '[]',
        "primary_key"          JSONB NOT NULL DEFAULT '[]',
        "foreign_keys"         JSONB NOT NULL DEFAULT '[]',
        "indexes"              JSONB NOT NULL DEFAULT '[]',
        "referenced_by_count"  INTEGER NOT NULL DEFAULT 0,
        "first_seen_at"        TIMESTAMPTZ NOT NULL DEFAULT now(),
        "last_seen_at"         TIMESTAMPTZ NOT NULL DEFAULT now(),
        "is_deleted"           BOOLEAN NOT NULL DEFAULT false,
        "created_at"           TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at"           TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_discovered_tables" PRIMARY KEY ("id"),
        CONSTRAINT "FK_discovered_tables_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_discovered_tables_connection" FOREIGN KEY ("connection_id") REFERENCES "db_connections"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_discovered_tables_schema" FOREIGN KEY ("schema_id") REFERENCES "discovered_schemas"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_discovered_tables_conn_fqn" ON "discovered_tables" ("connection_id", "full_qualified_name")`);
    await queryRunner.query(`CREATE INDEX "IDX_discovered_tables_tenant" ON "discovered_tables" ("tenant_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_discovered_tables_connection" ON "discovered_tables" ("connection_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_discovered_tables_fqn" ON "discovered_tables" ("full_qualified_name")`);
    await queryRunner.query(`CREATE INDEX "IDX_discovered_tables_slug" ON "discovered_tables" ("slug")`);

    // ── procedures ──
    await queryRunner.query(`
      CREATE TABLE "procedures" (
        "id"                    UUID DEFAULT uuid_generate_v4() NOT NULL,
        "tenant_id"             UUID NOT NULL,
        "connection_id"         UUID NOT NULL,
        "schema_id"             UUID,
        "analysis_job_id"       UUID,
        "object_type"           VARCHAR(50) NOT NULL,
        "schema_name"           VARCHAR(255) NOT NULL,
        "object_name"           VARCHAR(255) NOT NULL,
        "slug"                  VARCHAR(500) NOT NULL,
        "full_qualified_name"   VARCHAR(1000) NOT NULL,
        "raw_definition"        TEXT NOT NULL,
        "definition_hash"       VARCHAR(64) NOT NULL,
        "language"              VARCHAR(50) NOT NULL,
        "parameters"            JSONB NOT NULL DEFAULT '[]',
        "return_type"           VARCHAR(255),
        "is_deterministic"      BOOLEAN,
        "estimated_complexity"  INTEGER,
        "line_count"            INTEGER NOT NULL,
        "auto_doc"              JSONB,
        "security_findings"     JSONB NOT NULL DEFAULT '[]',
        "source_created_at"     TIMESTAMPTZ,
        "source_modified_at"    TIMESTAMPTZ,
        "first_seen_at"         TIMESTAMPTZ NOT NULL DEFAULT now(),
        "last_seen_at"          TIMESTAMPTZ NOT NULL DEFAULT now(),
        "is_deleted"            BOOLEAN NOT NULL DEFAULT false,
        "created_at"            TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at"            TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_procedures" PRIMARY KEY ("id"),
        CONSTRAINT "FK_procedures_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_procedures_connection" FOREIGN KEY ("connection_id") REFERENCES "db_connections"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_procedures_tenant" ON "procedures" ("tenant_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_procedures_connection" ON "procedures" ("connection_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_procedures_object_type" ON "procedures" ("object_type")`);
    await queryRunner.query(`CREATE INDEX "IDX_procedures_fqn" ON "procedures" ("full_qualified_name")`);
    await queryRunner.query(`CREATE INDEX "IDX_procedures_definition_hash" ON "procedures" ("definition_hash")`);
    await queryRunner.query(`CREATE INDEX "IDX_procedures_slug" ON "procedures" ("slug")`);

    // ── procedure_versions ──
    await queryRunner.query(`
      CREATE TABLE "procedure_versions" (
        "id"                 UUID DEFAULT uuid_generate_v4() NOT NULL,
        "procedure_id"       UUID NOT NULL,
        "version_number"     INTEGER NOT NULL,
        "raw_definition"     TEXT NOT NULL,
        "definition_hash"    VARCHAR(64) NOT NULL,
        "diff_from_previous" TEXT,
        "parameters"         JSONB NOT NULL DEFAULT '[]',
        "auto_doc"           JSONB,
        "detected_at"        TIMESTAMPTZ NOT NULL DEFAULT now(),
        "analysis_job_id"    UUID,
        CONSTRAINT "PK_procedure_versions" PRIMARY KEY ("id"),
        CONSTRAINT "FK_procedure_versions_procedure" FOREIGN KEY ("procedure_id") REFERENCES "procedures"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_procedure_versions_proc_version" ON "procedure_versions" ("procedure_id", "version_number")`);

    // ── dependencies ──
    await queryRunner.query(`
      CREATE TABLE "dependencies" (
        "id"                   UUID DEFAULT uuid_generate_v4() NOT NULL,
        "tenant_id"            UUID NOT NULL,
        "source_id"            UUID NOT NULL,
        "target_id"            UUID,
        "target_external_name" VARCHAR(500),
        "dependency_type"      VARCHAR(50) NOT NULL,
        "context"              JSONB NOT NULL DEFAULT '{}',
        "is_dynamic"           BOOLEAN NOT NULL DEFAULT false,
        "confidence"           REAL NOT NULL DEFAULT 1.0,
        "analysis_job_id"      UUID,
        "created_at"           TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_dependencies" PRIMARY KEY ("id"),
        CONSTRAINT "FK_dependencies_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_dependencies_source" FOREIGN KEY ("source_id") REFERENCES "procedures"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_dependencies_tenant" ON "dependencies" ("tenant_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_dependencies_source" ON "dependencies" ("source_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_dependencies_target" ON "dependencies" ("target_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_dependencies_type" ON "dependencies" ("dependency_type")`);

    // ── table_accesses ──
    await queryRunner.query(`
      CREATE TABLE "table_accesses" (
        "id"               UUID DEFAULT uuid_generate_v4() NOT NULL,
        "tenant_id"        UUID NOT NULL,
        "procedure_id"     UUID NOT NULL,
        "table_id"         UUID,
        "table_name"       VARCHAR(255) NOT NULL,
        "full_table_name"  VARCHAR(1000) NOT NULL,
        "operation"        VARCHAR(50) NOT NULL,
        "columns"          JSONB NOT NULL DEFAULT '[]',
        "line_number"      INTEGER,
        "is_temp_table"    BOOLEAN NOT NULL DEFAULT false,
        "is_dynamic"       BOOLEAN NOT NULL DEFAULT false,
        "confidence"       REAL NOT NULL DEFAULT 1.0,
        "analysis_job_id"  UUID,
        "created_at"       TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_table_accesses" PRIMARY KEY ("id"),
        CONSTRAINT "FK_table_accesses_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_table_accesses_procedure" FOREIGN KEY ("procedure_id") REFERENCES "procedures"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_table_accesses_tenant" ON "table_accesses" ("tenant_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_table_accesses_procedure" ON "table_accesses" ("procedure_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_table_accesses_table" ON "table_accesses" ("table_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_table_accesses_full_name" ON "table_accesses" ("full_table_name")`);

    // ── audit_logs ──
    await queryRunner.query(`
      CREATE TABLE "audit_logs" (
        "id"             UUID DEFAULT uuid_generate_v4() NOT NULL,
        "tenant_id"      UUID NOT NULL,
        "user_id"        UUID,
        "action"         VARCHAR(100) NOT NULL,
        "resource_type"  VARCHAR(100),
        "resource_id"    UUID,
        "details"        JSONB NOT NULL DEFAULT '{}',
        "ip_address"     VARCHAR(45),
        "user_agent"     VARCHAR(500),
        "created_at"     TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_audit_logs" PRIMARY KEY ("id"),
        CONSTRAINT "FK_audit_logs_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_audit_logs_tenant" ON "audit_logs" ("tenant_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_audit_logs_user" ON "audit_logs" ("user_id")`);
    await queryRunner.query(`CREATE INDEX "IDX_audit_logs_action" ON "audit_logs" ("action")`);
    await queryRunner.query(`CREATE INDEX "IDX_audit_logs_resource_type" ON "audit_logs" ("resource_type")`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "audit_logs" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "table_accesses" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "dependencies" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "procedure_versions" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "procedures" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "discovered_tables" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "discovered_schemas" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "analysis_jobs" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "db_connections" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "users" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "tenants" CASCADE`);
  }
}
