-- ═══════════════════════════════════════════════════════════════
-- SQLAtlas Demo: Oracle Banking System (PL/SQL)
-- Run against Oracle 19c+ / Oracle Free as TESTUSER
-- ═══════════════════════════════════════════════════════════════

-- ── Tables ──────────────────────────────────────────────────────

CREATE TABLE accounts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR2(200) NOT NULL,
    email VARCHAR2(255),
    account_number VARCHAR2(20) UNIQUE NOT NULL,
    account_type VARCHAR2(20) DEFAULT 'savings',
    balance NUMBER(18,2) DEFAULT 0,
    daily_limit NUMBER(18,2) DEFAULT 5000,
    monthly_limit NUMBER(18,2) DEFAULT 50000,
    status VARCHAR2(20) DEFAULT 'active',
    tier VARCHAR2(20) DEFAULT 'standard',
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE cards (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER REFERENCES accounts(id),
    card_number VARCHAR2(20) NOT NULL,
    card_type VARCHAR2(20) DEFAULT 'debit',
    expiry_month NUMBER,
    expiry_year NUMBER,
    status VARCHAR2(20) DEFAULT 'active',
    is_blocked NUMBER(1) DEFAULT 0,
    blocked_reason VARCHAR2(200)
);

CREATE TABLE transactions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER REFERENCES accounts(id),
    card_id NUMBER REFERENCES cards(id),
    amount NUMBER(18,2) NOT NULL,
    currency VARCHAR2(3) DEFAULT 'USD',
    trans_type VARCHAR2(20) NOT NULL,
    merchant_name VARCHAR2(200),
    merchant_category VARCHAR2(50),
    channel VARCHAR2(20) DEFAULT 'POS',
    auth_code VARCHAR2(20),
    status VARCHAR2(20) DEFAULT 'pending',
    risk_score NUMBER DEFAULT 0,
    description VARCHAR2(500),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE fraud_alerts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id NUMBER,
    account_id NUMBER REFERENCES accounts(id),
    alert_type VARCHAR2(50),
    risk_score NUMBER,
    action_taken VARCHAR2(50),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE activity_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR2(50),
    entity_id NUMBER,
    action VARCHAR2(50),
    actor VARCHAR2(100),
    details VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE settlements (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id NUMBER,
    amount NUMBER(18,2),
    fee NUMBER(18,2) DEFAULT 0,
    net_amount NUMBER(18,2),
    settlement_date DATE,
    batch_id VARCHAR2(50),
    status VARCHAR2(20) DEFAULT 'pending'
);

-- ── Audit Logging ───────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE sp_log_activity(
    p_entity_type IN VARCHAR2,
    p_entity_id   IN NUMBER,
    p_action      IN VARCHAR2,
    p_actor       IN VARCHAR2,
    p_details     IN VARCHAR2 DEFAULT NULL
) AS
BEGIN
    INSERT INTO activity_log(entity_type, entity_id, action, actor, details)
    VALUES (p_entity_type, p_entity_id, p_action, p_actor, p_details);
END;
/

-- ── Card Validation ─────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE sp_validate_card(
    p_card_number   IN  VARCHAR2,
    p_expiry_month  IN  NUMBER,
    p_expiry_year   IN  NUMBER,
    p_is_valid      OUT NUMBER,
    p_card_id       OUT NUMBER,
    p_account_id    OUT NUMBER,
    p_message       OUT VARCHAR2
) AS
    v_card cards%ROWTYPE;
    v_now_year  NUMBER := EXTRACT(YEAR FROM SYSDATE);
    v_now_month NUMBER := EXTRACT(MONTH FROM SYSDATE);
BEGIN
    p_is_valid := 0;

    BEGIN
        SELECT * INTO v_card FROM cards WHERE card_number = p_card_number;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            p_message := 'Card not found';
            RETURN;
    END;

    p_card_id := v_card.id;
    p_account_id := v_card.account_id;

    IF v_card.is_blocked = 1 THEN
        p_message := 'Card blocked: ' || NVL(v_card.blocked_reason, 'unknown');
        RETURN;
    END IF;

    IF v_card.status != 'active' THEN
        p_message := 'Card not active: ' || v_card.status;
        RETURN;
    END IF;

    IF p_expiry_year < v_now_year OR (p_expiry_year = v_now_year AND p_expiry_month < v_now_month) THEN
        p_message := 'Card expired';
        RETURN;
    END IF;

    p_is_valid := 1;
    p_message := 'Card valid';
END;
/

-- ── Balance Validation ──────────────────────────────────────────

CREATE OR REPLACE PROCEDURE sp_validate_balance(
    p_account_id    IN  NUMBER,
    p_amount        IN  NUMBER,
    p_is_sufficient OUT NUMBER,
    p_balance       OUT NUMBER,
    p_available     OUT NUMBER,
    p_message       OUT VARCHAR2
) AS
    v_account   accounts%ROWTYPE;
    v_daily     NUMBER;
    v_monthly   NUMBER;
BEGIN
    p_is_sufficient := 0;

    BEGIN
        SELECT * INTO v_account FROM accounts WHERE id = p_account_id;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            p_message := 'Account not found';
            RETURN;
    END;

    p_balance := v_account.balance;

    IF v_account.status != 'active' THEN
        p_message := 'Account not active: ' || v_account.status;
        RETURN;
    END IF;

    SELECT NVL(SUM(amount), 0) INTO v_daily
    FROM transactions
    WHERE account_id = p_account_id AND TRUNC(created_at) = TRUNC(SYSDATE) AND status = 'approved';

    SELECT NVL(SUM(amount), 0) INTO v_monthly
    FROM transactions
    WHERE account_id = p_account_id AND created_at >= TRUNC(SYSDATE, 'MM') AND status = 'approved';

    p_available := LEAST(v_account.balance, v_account.daily_limit - v_daily, v_account.monthly_limit - v_monthly);

    IF p_amount > p_available THEN
        p_message := 'Insufficient funds or limit exceeded';
        RETURN;
    END IF;

    p_is_sufficient := 1;
    p_message := 'Balance sufficient';
END;
/

-- ── Fraud Detection ─────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE sp_check_fraud(
    p_account_id        IN  NUMBER,
    p_amount            IN  NUMBER,
    p_merchant_category IN  VARCHAR2,
    p_channel           IN  VARCHAR2,
    p_is_flagged        OUT NUMBER,
    p_risk_score        OUT NUMBER,
    p_action            OUT VARCHAR2
) AS
    v_score         NUMBER := 0;
    v_recent_count  NUMBER;
    v_avg_amount    NUMBER;
    v_distinct_merch NUMBER;
    v_alert_type    VARCHAR2(50) := 'none';
BEGIN
    -- Rule 1: Velocity
    SELECT COUNT(*) INTO v_recent_count
    FROM transactions
    WHERE account_id = p_account_id AND created_at >= SYSTIMESTAMP - INTERVAL '1' HOUR AND status = 'approved';

    IF v_recent_count > 5 THEN
        v_score := v_score + 30;
        v_alert_type := 'velocity';
    END IF;

    -- Rule 2: Amount anomaly
    SELECT NVL(AVG(amount), 0) INTO v_avg_amount
    FROM transactions WHERE account_id = p_account_id AND status = 'approved';

    IF v_avg_amount > 0 AND p_amount > (v_avg_amount * 3) THEN
        v_score := v_score + 25;
        IF v_alert_type = 'none' THEN v_alert_type := 'amount_anomaly'; END IF;
    END IF;

    -- Rule 3: Multiple merchants
    SELECT COUNT(DISTINCT merchant_name) INTO v_distinct_merch
    FROM transactions
    WHERE account_id = p_account_id AND created_at >= SYSTIMESTAMP - INTERVAL '30' MINUTE AND status = 'approved';

    IF v_distinct_merch > 3 THEN
        v_score := v_score + 20;
        IF v_alert_type = 'none' THEN v_alert_type := 'multi_merchant'; END IF;
    END IF;

    -- Rule 4: High-risk category
    IF p_merchant_category IN ('gambling', 'crypto', 'money_transfer') THEN
        v_score := v_score + 15;
    END IF;

    -- Rule 5: Large ATM withdrawal
    IF p_channel = 'ATM' AND p_amount > 1000 THEN
        v_score := v_score + 10;
    END IF;

    -- Determine action
    IF v_score >= 70 THEN p_action := 'block';
    ELSIF v_score >= 40 THEN p_action := 'review';
    ELSE p_action := 'approve';
    END IF;

    p_risk_score := v_score;
    p_is_flagged := CASE WHEN v_score >= 40 THEN 1 ELSE 0 END;

    -- Log alert
    IF v_score > 30 THEN
        INSERT INTO fraud_alerts(account_id, alert_type, risk_score, action_taken)
        VALUES (p_account_id, v_alert_type, v_score, p_action);
    END IF;
END;
/

-- ── Settlement ──────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE sp_queue_settlement(
    p_transaction_id IN NUMBER,
    p_amount         IN NUMBER,
    p_fee_percent    IN NUMBER DEFAULT 2.5
) AS
    v_fee NUMBER;
    v_net NUMBER;
    v_id  NUMBER;
BEGIN
    v_fee := ROUND(p_amount * p_fee_percent / 100, 2);
    v_net := p_amount - v_fee;

    INSERT INTO settlements(transaction_id, amount, fee, net_amount, settlement_date, batch_id)
    VALUES (p_transaction_id, p_amount, v_fee, v_net, SYSDATE + 1, 'BATCH-' || TO_CHAR(SYSDATE, 'YYYYMMDD'))
    RETURNING id INTO v_id;

    sp_log_activity('settlement', v_id, 'queued', 'system', 'net=' || v_net);
END;
/

-- ══════════════════════════════════════════════════════════════════
-- MAIN SP: Process Card Transaction
-- ══════════════════════════════════════════════════════════════════

CREATE OR REPLACE PROCEDURE sp_process_transaction(
    p_card_number       IN  VARCHAR2,
    p_expiry_month      IN  NUMBER,
    p_expiry_year       IN  NUMBER,
    p_amount            IN  NUMBER,
    p_merchant_name     IN  VARCHAR2,
    p_merchant_category IN  VARCHAR2 DEFAULT 'retail',
    p_channel           IN  VARCHAR2 DEFAULT 'POS',
    p_transaction_id    OUT NUMBER,
    p_auth_code         OUT VARCHAR2,
    p_response_code     OUT VARCHAR2,
    p_response_message  OUT VARCHAR2,
    p_risk_score        OUT NUMBER
) AS
    v_card_valid    NUMBER;
    v_card_id       NUMBER;
    v_account_id    NUMBER;
    v_card_msg      VARCHAR2(500);
    v_bal_ok        NUMBER;
    v_balance       NUMBER;
    v_available     NUMBER;
    v_bal_msg       VARCHAR2(500);
    v_fraud_flagged NUMBER;
    v_fraud_action  VARCHAR2(50);
    v_email         VARCHAR2(255);
BEGIN
    p_response_code := '99';
    p_response_message := 'Processing error';
    p_risk_score := 0;

    -- Step 1: Validate card
    sp_validate_card(p_card_number, p_expiry_month, p_expiry_year, v_card_valid, v_card_id, v_account_id, v_card_msg);

    IF v_card_valid = 0 THEN
        p_response_code := '05';
        p_response_message := v_card_msg;
        RETURN;
    END IF;

    -- Step 2: Validate balance
    sp_validate_balance(v_account_id, p_amount, v_bal_ok, v_balance, v_available, v_bal_msg);

    IF v_bal_ok = 0 THEN
        p_response_code := '51';
        p_response_message := v_bal_msg;
        RETURN;
    END IF;

    -- Step 3: Fraud check
    sp_check_fraud(v_account_id, p_amount, p_merchant_category, p_channel, v_fraud_flagged, p_risk_score, v_fraud_action);

    IF v_fraud_action = 'block' THEN
        UPDATE cards SET is_blocked = 1, blocked_reason = 'Fraud score: ' || p_risk_score WHERE id = v_card_id;
        p_response_code := '59';
        p_response_message := 'Blocked by fraud detection';
        RETURN;
    END IF;

    -- Step 4: Create transaction
    p_auth_code := 'AUTH' || LPAD(TRUNC(DBMS_RANDOM.VALUE(0, 999999)), 6, '0');

    INSERT INTO transactions(account_id, card_id, amount, trans_type, merchant_name, merchant_category, channel, auth_code, status, risk_score)
    VALUES (v_account_id, v_card_id, p_amount, 'purchase', p_merchant_name, p_merchant_category, p_channel, p_auth_code,
        CASE WHEN v_fraud_action = 'review' THEN 'pending_review' ELSE 'approved' END, p_risk_score)
    RETURNING id INTO p_transaction_id;

    -- Step 5: Debit
    IF v_fraud_action != 'review' THEN
        UPDATE accounts SET balance = balance - p_amount WHERE id = v_account_id;
        sp_queue_settlement(p_transaction_id, p_amount);
    END IF;

    -- Step 6: Audit
    sp_log_activity('transaction', p_transaction_id, 'processed', 'system', 'amount=' || p_amount);

    p_response_code := '00';
    p_response_message := CASE WHEN v_fraud_action = 'review' THEN 'Approved - pending review' ELSE 'Approved' END;

    COMMIT;
END;
/

-- ── Reports ─────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE sp_generate_daily_report(p_date IN DATE DEFAULT SYSDATE) AS
    v_total_tx   NUMBER;
    v_total_amt  NUMBER;
    v_fraud      NUMBER;
    v_approved   NUMBER;
BEGIN
    SELECT COUNT(*), NVL(SUM(amount), 0) INTO v_total_tx, v_total_amt
    FROM transactions WHERE TRUNC(created_at) = TRUNC(p_date);

    SELECT COUNT(*) INTO v_fraud FROM fraud_alerts WHERE TRUNC(created_at) = TRUNC(p_date);

    SELECT COUNT(*) INTO v_approved
    FROM transactions WHERE TRUNC(created_at) = TRUNC(p_date) AND status = 'approved';

    sp_log_activity('report', 0, 'generated', 'system',
        'tx=' || v_total_tx || ' amount=' || v_total_amt || ' fraud=' || v_fraud);
END;
/

-- ── Tier Upgrade ────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION fn_check_tier(p_account_id IN NUMBER) RETURN VARCHAR2 AS
    v_volume    NUMBER;
    v_current   VARCHAR2(20);
    v_new_tier  VARCHAR2(20);
BEGIN
    SELECT tier INTO v_current FROM accounts WHERE id = p_account_id;

    SELECT NVL(SUM(amount), 0) INTO v_volume
    FROM transactions
    WHERE account_id = p_account_id AND created_at >= TRUNC(SYSDATE, 'MM') AND status = 'approved';

    v_new_tier := CASE
        WHEN v_volume >= 50000 THEN 'platinum'
        WHEN v_volume >= 20000 THEN 'gold'
        WHEN v_volume >= 5000  THEN 'silver'
        ELSE 'standard'
    END;

    IF v_new_tier != v_current THEN
        UPDATE accounts SET tier = v_new_tier WHERE id = p_account_id;
        sp_log_activity('account', p_account_id, 'tier_upgrade', 'system', v_current || '->' || v_new_tier);
    END IF;

    RETURN v_new_tier;
END;
/

-- ── Trigger ─────────────────────────────────────────────────────

CREATE OR REPLACE TRIGGER trg_auto_block_suspicious
    AFTER INSERT ON transactions
    FOR EACH ROW
    WHEN (NEW.risk_score >= 80)
BEGIN
    UPDATE cards SET is_blocked = 1, blocked_reason = 'Auto-blocked: score ' || :NEW.risk_score
    WHERE id = :NEW.card_id AND is_blocked = 0;
END;
/

-- ── Seed Data ───────────────────────────────────────────────────

INSERT INTO accounts(customer_name, email, account_number, balance, tier)
VALUES ('Demo User', 'demo@sqlatlas.dev', 'ORA-001', 25000.00, 'gold');

INSERT INTO cards(account_id, card_number, card_type, expiry_month, expiry_year)
VALUES (1, '4111111111110001', 'credit', 12, 2028);

COMMIT;
