#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────
# SQLAtlas — First-time setup script (Linux / macOS)
# Checks dependencies, generates secrets, creates .env, and starts services.
# Usage: ./scripts/setup.sh
# ─────────────────────────────────────────────────────────────────
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { printf "${CYAN}[INFO]${NC}  %s\n" "$1"; }
ok()    { printf "${GREEN}[OK]${NC}    %s\n" "$1"; }
warn()  { printf "${YELLOW}[WARN]${NC}  %s\n" "$1"; }
fail()  { printf "${RED}[FAIL]${NC}  %s\n" "$1"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DOCKER_DIR="$ROOT_DIR/docker"
ENV_FILE="$DOCKER_DIR/.env"

# ─── 1. Check dependencies ──────────────────────────────────────
info "Checking dependencies..."

check_cmd() {
  if command -v "$1" &>/dev/null; then
    ok "$1 found: $(command -v "$1")"
    return 0
  else
    return 1
  fi
}

MISSING=()

if ! check_cmd docker; then MISSING+=("docker"); fi
if ! docker compose version &>/dev/null 2>&1 && ! check_cmd docker-compose; then
  MISSING+=("docker-compose")
fi

# Node/pnpm only needed for local dev (not Docker-only)
HAS_NODE=false
if check_cmd node; then
  NODE_VER=$(node -v | sed 's/v//')
  NODE_MAJOR=$(echo "$NODE_VER" | cut -d. -f1)
  if [ "$NODE_MAJOR" -ge 20 ]; then
    ok "Node.js $NODE_VER (>= 20 required)"
    HAS_NODE=true
  else
    warn "Node.js $NODE_VER found, but >= 20.0.0 required for local dev"
  fi
fi

HAS_PNPM=false
if check_cmd pnpm; then
  HAS_PNPM=true
fi

HAS_PYTHON=false
if check_cmd python3; then
  PY_VER=$(python3 --version | awk '{print $2}')
  PY_MAJOR=$(echo "$PY_VER" | cut -d. -f1)
  PY_MINOR=$(echo "$PY_VER" | cut -d. -f2)
  if [ "$PY_MAJOR" -ge 3 ] && [ "$PY_MINOR" -ge 11 ]; then
    ok "Python $PY_VER (>= 3.11 required)"
    HAS_PYTHON=true
  else
    warn "Python $PY_VER found, but >= 3.11 required for local dev"
  fi
fi

if [ ${#MISSING[@]} -gt 0 ]; then
  fail "Missing required dependencies: ${MISSING[*]}\nInstall them and re-run this script."
fi

echo ""

# ─── 2. Generate .env file ──────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
  warn ".env already exists at $ENV_FILE"
  read -rp "  Overwrite? (y/N): " OVERWRITE
  if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
    info "Keeping existing .env"
  else
    rm "$ENV_FILE"
  fi
fi

if [ ! -f "$ENV_FILE" ]; then
  info "Generating secrets and .env file..."

  # Generate secure random values
  DB_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)
  JWT_SECRET=$(openssl rand -base64 48)
  ENCRYPTION_KEY=$(openssl rand -hex 32)

  # Ask for admin credentials (optional)
  echo ""
  info "Optional: Pre-configure admin account (skip with Enter for web wizard)"
  read -rp "  Admin email (leave empty to skip): " ADMIN_EMAIL
  ADMIN_PASSWORD=""
  ADMIN_DISPLAY_NAME=""
  ORG_NAME=""

  if [ -n "$ADMIN_EMAIL" ]; then
    while true; do
      read -rsp "  Admin password (min 8 chars, upper+lower+number+special): " ADMIN_PASSWORD
      echo ""
      if [ ${#ADMIN_PASSWORD} -ge 8 ]; then
        break
      fi
      warn "Password too short, try again"
    done
    read -rp "  Display name [Admin]: " ADMIN_DISPLAY_NAME
    ADMIN_DISPLAY_NAME="${ADMIN_DISPLAY_NAME:-Admin}"
    read -rp "  Organization name [My Organization]: " ORG_NAME
    ORG_NAME="${ORG_NAME:-My Organization}"
  fi

  cat > "$ENV_FILE" <<EOF
# SQLAtlas — Generated by setup.sh on $(date -Iseconds)
# ── Database ──
POSTGRES_USER=sqlatlas
POSTGRES_PASSWORD=$DB_PASSWORD
POSTGRES_DB=sqlatlas

# ── Security ──
JWT_SECRET=$JWT_SECRET
CREDENTIAL_ENCRYPTION_KEY=$ENCRYPTION_KEY

# ── Auth ──
REGISTRATION_MODE=closed
MULTI_TENANT=false

# ── Ports ──
API_PORT=3000
WEB_PORT=5173
PARSER_PORT=8100
DB_PORT=5433
REDIS_PORT=6380

# ── CORS ──
CORS_ORIGINS=http://localhost:5173,http://localhost:3000
EOF

  if [ -n "$ADMIN_EMAIL" ]; then
    cat >> "$ENV_FILE" <<EOF

# ── Auto-setup admin ──
ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_PASSWORD=$ADMIN_PASSWORD
ADMIN_DISPLAY_NAME=$ADMIN_DISPLAY_NAME
ORG_NAME=$ORG_NAME
EOF
  fi

  ok ".env created at $ENV_FILE"
  echo ""
fi

# ─── 3. Create api-gateway .env for local dev ───────────────────
API_ENV="$ROOT_DIR/apps/api-gateway/.env"
if [ ! -f "$API_ENV" ] && [ "$HAS_NODE" = true ]; then
  info "Creating api-gateway .env for local development..."
  # Source the docker .env to reuse the same secrets
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  cat > "$API_ENV" <<EOF
NODE_ENV=development
PORT=3000
API_PREFIX=api/v1
DB_HOST=localhost
DB_PORT=${DB_PORT:-5433}
DB_USERNAME=${POSTGRES_USER:-sqlatlas}
DB_PASSWORD=${POSTGRES_PASSWORD}
DB_DATABASE=${POSTGRES_DB:-sqlatlas}
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRATION=15m
JWT_REFRESH_EXPIRATION=7d
PARSING_ENGINE_URL=http://localhost:${PARSER_PORT:-8100}
REDIS_HOST=localhost
REDIS_PORT=${REDIS_PORT:-6380}
CREDENTIAL_BACKEND=aes
CREDENTIAL_ENCRYPTION_KEY=${CREDENTIAL_ENCRYPTION_KEY}
CORS_ORIGINS=http://localhost:5173,http://localhost:3000
REGISTRATION_MODE=${REGISTRATION_MODE:-closed}
MULTI_TENANT=${MULTI_TENANT:-false}
EOF

  if [ -n "${ADMIN_EMAIL:-}" ]; then
    cat >> "$API_ENV" <<EOF
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_DISPLAY_NAME=${ADMIN_DISPLAY_NAME:-Admin}
ORG_NAME=${ORG_NAME:-My Organization}
EOF
  fi

  ok "api-gateway .env created"
fi

# ─── 4. Start services ──────────────────────────────────────────
echo ""
info "Starting Docker services..."

cd "$DOCKER_DIR"

if docker compose version &>/dev/null 2>&1; then
  COMPOSE="docker compose"
else
  COMPOSE="docker-compose"
fi

$COMPOSE --env-file "$ENV_FILE" up -d postgres redis

info "Waiting for PostgreSQL to be ready..."
for i in $(seq 1 30); do
  if $COMPOSE exec -T postgres pg_isready -U "${POSTGRES_USER:-sqlatlas}" &>/dev/null; then
    ok "PostgreSQL is ready"
    break
  fi
  if [ "$i" -eq 30 ]; then fail "PostgreSQL did not start in time"; fi
  sleep 1
done

info "Waiting for Redis to be ready..."
for i in $(seq 1 15); do
  if $COMPOSE exec -T redis redis-cli ping 2>/dev/null | grep -q PONG; then
    ok "Redis is ready"
    break
  fi
  if [ "$i" -eq 15 ]; then fail "Redis did not start in time"; fi
  sleep 1
done

# ─── 5. Summary ─────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════════════════════"
printf "${GREEN} SQLAtlas setup complete!${NC}\n"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  Infrastructure:"
echo "    PostgreSQL : localhost:${DB_PORT:-5433}"
echo "    Redis      : localhost:${REDIS_PORT:-6380}"
echo ""

if [ "$HAS_NODE" = true ] && [ "$HAS_PNPM" = true ]; then
  echo "  Next steps (local development):"
  echo "    1. pnpm install"
  echo "    2. cd apps/parsing-engine && uv sync && cd ../.."
  echo "    3. Terminal 1: cd apps/parsing-engine && uv run uvicorn src.main:app --port 8100 --reload"
  echo "    4. Terminal 2: cd apps/api-gateway && pnpm dev"
  echo "    5. Terminal 3: cd apps/web-client && pnpm dev"
  echo "    6. Open http://localhost:5173"
else
  echo "  Next steps (Docker only):"
  echo "    1. cd docker && $COMPOSE --env-file .env up -d"
  echo "    2. Open http://localhost:3000"
fi

echo ""
if [ -n "${ADMIN_EMAIL:-}" ]; then
  echo "  Admin account: ${ADMIN_EMAIL} (created on first API boot)"
else
  echo "  First visit: http://localhost:5173/setup (or :3000 in Docker)"
  echo "  The setup wizard will create your admin account."
fi
echo ""
echo "  Docs:   http://localhost:3000/docs (Swagger, dev mode only)"
echo ""
