# ─────────────────────────────────────────────────────────────────
# SQLAtlas — First-time setup script (Windows PowerShell)
# Checks dependencies, generates secrets, creates .env, and starts services.
# Usage: .\scripts\setup.ps1
# ─────────────────────────────────────────────────────────────────
$ErrorActionPreference = "Stop"

function Write-Info  { Write-Host "[INFO]  $args" -ForegroundColor Cyan }
function Write-Ok    { Write-Host "[OK]    $args" -ForegroundColor Green }
function Write-Warn  { Write-Host "[WARN]  $args" -ForegroundColor Yellow }
function Write-Fail  { Write-Host "[FAIL]  $args" -ForegroundColor Red; exit 1 }

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir   = Split-Path -Parent $ScriptDir
$DockerDir = Join-Path $RootDir "docker"
$EnvFile   = Join-Path $DockerDir ".env"

# ─── 1. Check dependencies ──────────────────────────────────────
Write-Info "Checking dependencies..."

$Missing = @()

if (Get-Command docker -ErrorAction SilentlyContinue) {
    Write-Ok "docker found"
} else {
    $Missing += "docker"
}

try {
    docker compose version 2>$null | Out-Null
    Write-Ok "docker compose found"
} catch {
    $Missing += "docker-compose"
}

$HasNode = $false
if (Get-Command node -ErrorAction SilentlyContinue) {
    $NodeVer = (node -v) -replace "v", ""
    $NodeMajor = [int]($NodeVer.Split(".")[0])
    if ($NodeMajor -ge 20) {
        Write-Ok "Node.js $NodeVer (>= 20 required)"
        $HasNode = $true
    } else {
        Write-Warn "Node.js $NodeVer found, but >= 20.0.0 required for local dev"
    }
}

$HasPnpm = $false
if (Get-Command pnpm -ErrorAction SilentlyContinue) {
    Write-Ok "pnpm found"
    $HasPnpm = $true
}

$HasPython = $false
if (Get-Command python -ErrorAction SilentlyContinue) {
    $PyVer = (python --version 2>&1) -replace "Python ", ""
    $PyParts = $PyVer.Split(".")
    if ([int]$PyParts[0] -ge 3 -and [int]$PyParts[1] -ge 11) {
        Write-Ok "Python $PyVer (>= 3.11 required)"
        $HasPython = $true
    } else {
        Write-Warn "Python $PyVer found, but >= 3.11 required for local dev"
    }
}

if ($Missing.Count -gt 0) {
    Write-Fail "Missing required dependencies: $($Missing -join ', '). Install them and re-run."
}

Write-Host ""

# ─── 2. Generate .env file ──────────────────────────────────────
if (Test-Path $EnvFile) {
    Write-Warn ".env already exists at $EnvFile"
    $Overwrite = Read-Host "  Overwrite? (y/N)"
    if ($Overwrite -ne "y" -and $Overwrite -ne "Y") {
        Write-Info "Keeping existing .env"
    } else {
        Remove-Item $EnvFile
    }
}

if (-not (Test-Path $EnvFile)) {
    Write-Info "Generating secrets and .env file..."

    # Generate secure random values
    $bytes = New-Object byte[] 24
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    $DbPassword = [Convert]::ToBase64String($bytes) -replace "[/+=]", "" | ForEach-Object { $_.Substring(0, [Math]::Min(24, $_.Length)) }

    $bytes = New-Object byte[] 48
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    $JwtSecret = [Convert]::ToBase64String($bytes)

    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    $EncryptionKey = ($bytes | ForEach-Object { $_.ToString("x2") }) -join ""

    # Ask for admin credentials
    Write-Host ""
    Write-Info "Optional: Pre-configure admin account (skip with Enter for web wizard)"
    $AdminEmail = Read-Host "  Admin email (leave empty to skip)"
    $AdminPassword = ""
    $AdminDisplayName = ""
    $OrgName = ""

    if ($AdminEmail) {
        do {
            $SecurePass = Read-Host "  Admin password (min 8 chars)" -AsSecureString
            $AdminPassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecurePass))
            if ($AdminPassword.Length -lt 8) { Write-Warn "Password too short, try again" }
        } while ($AdminPassword.Length -lt 8)

        $AdminDisplayName = Read-Host "  Display name [Admin]"
        if (-not $AdminDisplayName) { $AdminDisplayName = "Admin" }
        $OrgName = Read-Host "  Organization name [My Organization]"
        if (-not $OrgName) { $OrgName = "My Organization" }
    }

    $EnvContent = @"
# SQLAtlas — Generated by setup.ps1 on $(Get-Date -Format o)
# ── Database ──
POSTGRES_USER=sqlatlas
POSTGRES_PASSWORD=$DbPassword
POSTGRES_DB=sqlatlas

# ── Security ──
JWT_SECRET=$JwtSecret
CREDENTIAL_ENCRYPTION_KEY=$EncryptionKey

# ── Auth ──
REGISTRATION_MODE=closed
MULTI_TENANT=false

# ── Ports ──
API_PORT=3000
WEB_PORT=5173
PARSER_PORT=8100
DB_PORT=5433
REDIS_PORT=6380

# ── CORS ──
CORS_ORIGINS=http://localhost:5173,http://localhost:3000
"@

    if ($AdminEmail) {
        $EnvContent += @"

# ── Auto-setup admin ──
ADMIN_EMAIL=$AdminEmail
ADMIN_PASSWORD=$AdminPassword
ADMIN_DISPLAY_NAME=$AdminDisplayName
ORG_NAME=$OrgName
"@
    }

    Set-Content -Path $EnvFile -Value $EnvContent -Encoding UTF8
    Write-Ok ".env created at $EnvFile"
    Write-Host ""
}

# ─── 3. Create api-gateway .env for local dev ───────────────────
$ApiEnv = Join-Path $RootDir "apps\api-gateway\.env"
if (-not (Test-Path $ApiEnv) -and $HasNode) {
    Write-Info "Creating api-gateway .env for local development..."

    # Read generated values from docker .env
    $envVars = @{}
    Get-Content $EnvFile | ForEach-Object {
        if ($_ -match "^([^#][^=]+)=(.*)$") {
            $envVars[$Matches[1].Trim()] = $Matches[2].Trim()
        }
    }

    $ApiEnvContent = @"
NODE_ENV=development
PORT=3000
API_PREFIX=api/v1
DB_HOST=localhost
DB_PORT=$($envVars['DB_PORT'] ?? '5433')
DB_USERNAME=$($envVars['POSTGRES_USER'] ?? 'sqlatlas')
DB_PASSWORD=$($envVars['POSTGRES_PASSWORD'])
DB_DATABASE=$($envVars['POSTGRES_DB'] ?? 'sqlatlas')
JWT_SECRET=$($envVars['JWT_SECRET'])
JWT_EXPIRATION=15m
JWT_REFRESH_EXPIRATION=7d
PARSING_ENGINE_URL=http://localhost:$($envVars['PARSER_PORT'] ?? '8100')
REDIS_HOST=localhost
REDIS_PORT=$($envVars['REDIS_PORT'] ?? '6380')
CREDENTIAL_BACKEND=aes
CREDENTIAL_ENCRYPTION_KEY=$($envVars['CREDENTIAL_ENCRYPTION_KEY'])
CORS_ORIGINS=http://localhost:5173,http://localhost:3000
REGISTRATION_MODE=$($envVars['REGISTRATION_MODE'] ?? 'closed')
MULTI_TENANT=$($envVars['MULTI_TENANT'] ?? 'false')
"@

    if ($envVars['ADMIN_EMAIL']) {
        $ApiEnvContent += @"

ADMIN_EMAIL=$($envVars['ADMIN_EMAIL'])
ADMIN_PASSWORD=$($envVars['ADMIN_PASSWORD'])
ADMIN_DISPLAY_NAME=$($envVars['ADMIN_DISPLAY_NAME'] ?? 'Admin')
ORG_NAME=$($envVars['ORG_NAME'] ?? 'My Organization')
"@
    }

    Set-Content -Path $ApiEnv -Value $ApiEnvContent -Encoding UTF8
    Write-Ok "api-gateway .env created"
}

# ─── 4. Start services ──────────────────────────────────────────
Write-Host ""
Write-Info "Starting Docker services..."

Push-Location $DockerDir

docker compose --env-file $EnvFile up -d postgres redis

Write-Info "Waiting for PostgreSQL to be ready..."
for ($i = 1; $i -le 30; $i++) {
    try {
        $result = docker compose exec -T postgres pg_isready -U sqlatlas 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Ok "PostgreSQL is ready"
            break
        }
    } catch {}
    if ($i -eq 30) { Write-Fail "PostgreSQL did not start in time" }
    Start-Sleep -Seconds 1
}

Write-Info "Waiting for Redis to be ready..."
for ($i = 1; $i -le 15; $i++) {
    try {
        $result = docker compose exec -T redis redis-cli ping 2>&1
        if ($result -match "PONG") {
            Write-Ok "Redis is ready"
            break
        }
    } catch {}
    if ($i -eq 15) { Write-Fail "Redis did not start in time" }
    Start-Sleep -Seconds 1
}

Pop-Location

# ─── 5. Summary ─────────────────────────────────────────────────
Write-Host ""
Write-Host "==================================================================" -ForegroundColor Green
Write-Host " SQLAtlas setup complete!" -ForegroundColor Green
Write-Host "==================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Infrastructure:"
Write-Host "    PostgreSQL : localhost:$($envVars['DB_PORT'] ?? '5433')"
Write-Host "    Redis      : localhost:$($envVars['REDIS_PORT'] ?? '6380')"
Write-Host ""

if ($HasNode -and $HasPnpm) {
    Write-Host "  Next steps (local development):"
    Write-Host "    1. pnpm install"
    Write-Host "    2. cd apps\parsing-engine; uv sync; cd ..\.."
    Write-Host "    3. Terminal 1: cd apps\parsing-engine; uv run uvicorn src.main:app --port 8100 --reload"
    Write-Host "    4. Terminal 2: cd apps\api-gateway; pnpm dev"
    Write-Host "    5. Terminal 3: cd apps\web-client; pnpm dev"
    Write-Host "    6. Open http://localhost:5173"
} else {
    Write-Host "  Next steps (Docker only):"
    Write-Host "    1. cd docker; docker compose --env-file .env up -d"
    Write-Host "    2. Open http://localhost:3000"
}

Write-Host ""
if ($AdminEmail) {
    Write-Host "  Admin account: $AdminEmail (created on first API boot)"
} else {
    Write-Host "  First visit: http://localhost:5173/setup (or :3000 in Docker)"
    Write-Host "  The setup wizard will create your admin account."
}
Write-Host ""
Write-Host "  Docs:   http://localhost:3000/docs (Swagger, dev mode only)"
Write-Host ""
